version: '3'
services:
  postgres:
    image: postgres:10.5-alpine
    volumes:
        - ./create_weather_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn run dev
    depends_on:
      - postgres
    ports:
      - 3333:3333